### PR TITLE
Rewrote `spatial_ref::srs::tests::from_proj4_to_wkt`...

### LINKED ISSUE #441: `spatial_ref::srs::tests::from_proj4_to_wkt` macOS test regression
The test `spatial_ref::srs::tests::from_proj4_to_wkt` is failing on macOS under GDAL `3.7.1` and Proj `9.2.1`.

The only difference appears to be the `DATUM` description:

`Unknown based on GRS 1980 ellipsoid`  
vs  
`Unknown based on GRS80 ellipsoid`

## Output

```
---- spatial_ref::srs::tests::from_proj4_to_wkt stdout ----
thread 'spatial_ref::srs::tests::from_proj4_to_wkt' panicked at 'assertion failed: `(left == right)`
  left: `"PROJCS[\"unknown\",GEOGCS[\"unknown\",DATUM[\"Unknown based on GRS 1980 ellipsoid\",SPHEROID[\"GRS 1980\",6378137,298.257222101,AUTHORITY[\"EPSG\",\"7019\"]]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]]],PROJECTION[\"Lambert_Azimuthal_Equal_Area\"],PARAMETER[\"latitude_of_center\",52],PARAMETER[\"longitude_of_center\",10],PARAMETER[\"false_easting\",4321000],PARAMETER[\"false_northing\",3210000],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH]]"`,
 right: `"PROJCS[\"unknown\",GEOGCS[\"unknown\",DATUM[\"Unknown based on GRS80 ellipsoid\",SPHEROID[\"GRS 1980\",6378137,298.257222101,AUTHORITY[\"EPSG\",\"7019\"]]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]]],PROJECTION[\"Lambert_Azimuthal_Equal_Area\"],PARAMETER[\"latitude_of_center\",52],PARAMETER[\"longitude_of_center\",10],PARAMETER[\"false_easting\",4321000],PARAMETER[\"false_northing\",3210000],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH]]"`', src/spatial_ref/srs.rs:638:9
```

## Build Details

```
GDALVersionInfo {
    RELEASE_NAME: "3.7.1"
    RELEASE_DATE: "20230706"
    VERSION_NUM: "3070100"
    BUILD_INFO {
        CURL_ENABLED: "YES"
        PAM_ENABLED: "YES"
        GEOS_ENABLED: "YES"
        OGR_ENABLED: "YES"
        GEOS_VERSION: "3.12.0-CAPI-1.18.0"
        CURL_VERSION: "7.79.1"
        PROJ_RUNTIME_VERSION: "9.2.1"
        PROJ_BUILD_VERSION: "9.2.1"
        COMPILER: "clang 14.0.0 (clang-1400.0.29.202)"
    }
}
```

```
$ uname -a
Darwin  21.6.0 Darwin Kernel Version 21.6.0: Thu Jun  8 23:56:13 PDT 2023; root:xnu-8020.240.18.701.6~1/RELEASE_ARM64_T6000 arm64
```

### PR DESCRIPTION
**Pull request by metasim**
...to be less sensitive to Proj database changes.

- [X] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [X] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Also added `examples/version.rs` to make it easy to report GDAL build info with bug reports.

Closes #441

### CODE REVIEW

File: src/spatial_ref/srs.rs [hunk 1]
```diff
@@ -631,11 +631,9 @@ mod tests {
...
-        assert_eq!(spatial_ref.to_wkt().unwrap(), "PROJCS[\"unnamed\",GEOGCS[\"GRS 1980(IUGG, 1980)\",DATUM[\"unknown\",SPHEROID[\"GRS80\",6378137,298.257222101]],PRIMEM[\"Greenwich\",0],UNIT[\"degree\",0.0174532925199433]],PROJECTION[\"Lambert_Azimuthal_Equal_Area\"],PARAMETER[\"latitude_of_center\",52],PARAMETER[\"longitude_of_center\",10],PARAMETER[\"false_easting\",4321000],PARAMETER[\"false_northing\",3210000],UNIT[\"Meter\",1]]");
-        #[cfg(major_ge_3)]
-        assert_eq!(spatial_ref.to_wkt().unwrap(), "PROJCS[\"unknown\",GEOGCS[\"unknown\",DATUM[\"Unknown based on GRS80 ellipsoid\",SPHEROID[\"GRS 1980\",6378137,298.257222101,AUTHORITY[\"EPSG\",\"7019\"]]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]]],PROJECTION[\"Lambert_Azimuthal_Equal_Area\"],PARAMETER[\"latitude_of_center\",52],PARAMETER[\"longitude_of_center\",10],PARAMETER[\"false_easting\",4321000],PARAMETER[\"false_northing\",3210000],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH]]");
+
+        let round_trip = SpatialRef::from_wkt(&spatial_ref.to_wkt().unwrap()).unwrap();
```
Comment (lnicola) [inline src/spatial_ref/srs.rs:635]: Let's also do a `contains` for `GRS` and `80`. I wouldn't expect that to break too soon.
