### PR TITLE
Make string conversion fallible

### LINKED ISSUE #588: Unsoundness in "_string" and "_pathbuf"
**Describe the bug**
The _string and _pathbuf functions use CStr::from_ptr to convert a raw pointer (*const c_char) into a CStr. However, the functions do not validate that the pointer meets the necessary safety requirements. This may lead to Undefined Behavior (UB) if the pointer is invalid, null, or if the data it references is not null-terminated.
https://github.com/georust/gdal/blob/2c673d6a885d1299b8c7ce8cb0818e7e6dac43e6/src/utils.rs#L8
https://github.com/georust/gdal/blob/2c673d6a885d1299b8c7ce8cb0818e7e6dac43e6/src/utils.rs#L25
```
pub fn _string(raw_ptr: *const c_char) -> String {
    let c_str = unsafe { CStr::from_ptr(raw_ptr) };
    c_str.to_string_lossy().into_owned()
}
pub fn _pathbuf(raw_ptr: *const c_char) -> PathBuf {
    let c_str = unsafe { CStr::from_ptr(raw_ptr) };
    c_str.to_string_lossy().into_owned().into()
}
```
**To Reproduce**
Provide a null pointer:
```
let null_ptr: *const c_char = std::ptr::null();
let result = _string(null_ptr); // UB: Null pointer
```
**Expected behavior**
The functions should validate the input pointer to ensure that:

It is not null.
It points to valid memory.
It references a null-terminated C string.
The functions should gracefully handle invalid inputs by returning an appropriate error instead of invoking Undefined Behavior.
**Additional context**
Expected behavior includes:

Validating the raw pointer before dereferencing it.
Ensuring the memory it points to is a valid, null-terminated C string.

### PR DESCRIPTION
**Pull request by lnicola**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Closes #588

This makes `_string` and `_pathbuf` fallible and updates the callers to some sensible defaults (by returning empty strings in many places, which seems similar in spirit to what GDAL does). There's an API change on `SpatialRef::authority_name` and some friends, which used to return `Result`, but where `Option` feels more appropriate for what they're doing. It might be a little annoying for the users, though.

### CODE REVIEW

File: src/vector/ops/conversions/formats.rs [hunk 1]
```diff
@@ -92,8 +92,8 @@ impl Geometry {
                 method_name: "OGR_G_ExportToWkt",
             });
         }
-        let wkt = _string(c_wkt);
-        unsafe { gdal_sys::OGRFree(c_wkt as *mut c_void) };
+        let wkt = _string(c_wkt).unwrap_or_default();
+        unsafe { gdal_sys::VSIFree(c_wkt as *mut c_void) };
```
Comment (lnicola) [inline src/vector/ops/conversions/formats.rs:96]: `OGRFree` is deprecated.

File: src/gcp.rs [hunk 2]
```diff
@@ -81,8 +81,8 @@ impl<'p> GcpRef<'p> {
 impl From<&gdal_sys::GDAL_GCP> for Gcp {
     fn from(gcp: &gdal_sys::GDAL_GCP) -> Self {
         Gcp {
-            id: _string(gcp.pszId),
-            info: _string(gcp.pszId),
+            id: _string(gcp.pszId).unwrap_or_default(),
+            info: _string(gcp.pszInfo).unwrap_or_default(),
```
Comment (lnicola) [inline src/gcp.rs:85]: :see_no_evil:

File: src/version.rs [hunk 3]
```diff
@@ -54,7 +54,8 @@ use std::fmt::Write;
 /// Details: [`const char *GDALVersionInfo(const char*)`](https://gdal.org/api/raster_c_api.html#_CPPv415GDALVersionInfoPKc)
 pub fn version_info(key: &str) -> String {
     let c_key = CString::new(key.as_bytes()).unwrap();
-    _string(unsafe { gdal_sys::GDALVersionInfo(c_key.as_ptr()) })
+    let rv = unsafe { gdal_sys::GDALVersionInfo(c_key.as_ptr()) };
```
Comment (weiznich) [inline src/version.rs:57]: Do we need to free `rv` here? I assume that this is the equivalent of a `&'static str` on the c side, right?

File: src/vector/layer.rs [hunk 4]
```diff
@@ -284,7 +284,7 @@ pub trait LayerAccess: Sized {
     /// Get the name of this layer.
     fn name(&self) -> String {
         let rv = unsafe { gdal_sys::OGR_L_GetName(self.c_layer()) };
```
Comment (weiznich) [inline src/vector/layer.rs:286]: We don't need to free `rv` here because it's owned by the layer?

File: src/vector/geometry.rs [hunk 5]
```diff
@@ -358,9 +354,7 @@ impl Eq for Geometry {}
 
 pub fn geometry_type_to_name(ty: OGRwkbGeometryType::Type) -> String {
     let rv = unsafe { gdal_sys::OGRGeometryTypeToName(ty) };
```
Comment (weiznich) [inline src/vector/geometry.rs:356]: We don't need to free `rv` here as it's essentially a static str, right?

File: src/vector/geometry.rs [hunk 6]
```diff
@@ -170,11 +170,7 @@ impl Geometry {
         // Note: C API makes no statements about this possibly returning null.
         // So we don't have to result wrap this,
         let c_str = unsafe { gdal_sys::OGR_G_GetGeometryName(self.c_geometry()) };
```
Comment (weiznich) [inline src/vector/geometry.rs:172]: This is essentially a static string, right?

File: src/vector/feature.rs [hunk 7]
```diff
@@ -835,7 +834,7 @@ impl FieldValue {
 
 pub fn field_type_to_name(ty: OGRFieldType::Type) -> String {
     let rv = unsafe { gdal_sys::OGR_GetFieldTypeName(ty) };
-    _string(rv)
+    _string(rv).unwrap_or_default()
```
Comment (weiznich) [inline src/vector/feature.rs:837]: `rv` is a static string here, right?

File: src/vector/feature.rs [hunk 8]
```diff
@@ -625,13 +624,13 @@ impl<'a> Iterator for FieldValueIterator<'a> {
             let field_defn =
                 unsafe { gdal_sys::OGR_F_GetFieldDefnRef(self.feature.c_feature, idx as c_int) };
             let field_name = unsafe { gdal_sys::OGR_Fld_GetNameRef(field_defn) };
```
Comment (weiznich) [inline src/vector/feature.rs:626]: `field_name` is owned by `field_defn` so we wont need to free it, right?

File: src/vector/feature.rs [hunk 9]
```diff
@@ -90,7 +90,7 @@ impl<'a> Feature<'a> {
         match field_type {
             OGRFieldType::OFTString => {
                 let rv = unsafe { gdal_sys::OGR_F_GetFieldAsString(self.c_feature, field_idx) };
```
Comment (weiznich) [inline src/vector/feature.rs:92]: `rv` is owned by `c_feature` so we don't need to free it?

File: src/vector/defn.rs [hunk 10]
```diff
@@ -206,7 +203,7 @@ impl<'a> GeomField<'a> {
     /// Get the name of this field.
     pub fn name(&'a self) -> String {
         let rv = unsafe { gdal_sys::OGR_GFld_GetNameRef(self.c_field_defn) };
```
Comment (weiznich) [inline src/vector/defn.rs:205]: `rv` is owned by `c_field_defn` so we don't need to free it?

File: src/vector/defn.rs [hunk 11]
```diff
@@ -162,11 +162,8 @@ impl<'a> Field<'a> {
 
     /// Get default field value.
     pub fn default_value(&'a self) -> Option<String> {
-        let rv = unsafe { gdal_sys::OGR_Fld_GetDefault(self.c_field_defn) };
-        if rv.is_null() {
-            return None;
-        }
-        Some(_string(rv))
+        let c_ptr = unsafe { gdal_sys::OGR_Fld_GetDefault(self.c_field_defn) };
```
Comment (weiznich) [inline src/vector/defn.rs:165]: `c_ptr` is owned by `c_field_defn` so we don't need to free it here?

File: src/vector/defn.rs [hunk 12]
```diff
@@ -122,13 +122,13 @@ impl<'a> Field<'a> {
     /// Get the name of this field.
     pub fn name(&'a self) -> String {
         let rv = unsafe { gdal_sys::OGR_Fld_GetNameRef(self.c_field_defn) };
-        _string(rv)
+        _string(rv).unwrap_or_default()
     }
 
     /// Get the alternative name (alias) of this field.
     pub fn alternative_name(&'a self) -> String {
         let rv = unsafe { gdal_sys::OGR_Fld_GetAlternativeNameRef(self.c_field_defn) };
```
Comment (weiznich) [inline src/vector/defn.rs:130]: `rv` is owned by `c_field_defn` here so we don't need to free it?

File: src/utils.rs [hunk 13]
```diff
@@ -5,9 +5,13 @@ use gdal_sys::CPLErr;
 
 use crate::errors::*;
 
-pub fn _string(raw_ptr: *const c_char) -> String {
-    let c_str = unsafe { CStr::from_ptr(raw_ptr) };
-    c_str.to_string_lossy().into_owned()
+pub fn _string(raw_ptr: *const c_char) -> Option<String> {
```
Comment (weiznich) [inline src/utils.rs:8]: It might be worth to add a documentation comment to this function and to `__pathbuf` to point out that they perform null checks internally.

File: src/spatial_ref/srs.rs [hunk 14]
```diff
@@ -580,12 +567,8 @@ impl SpatialRef {
         let child = child.try_into().expect("`child` must fit in `c_int`");
 
         let c_node_path = CString::new(node_path)?;
-        let rv = unsafe { gdal_sys::OSRGetAttrValue(self.0, c_node_path.as_ptr(), child) };
-        if rv.is_null() {
-            Ok(None)
-        } else {
-            Ok(Some(_string(rv)))
-        }
+        let c_ptr = unsafe { gdal_sys::OSRGetAttrValue(self.0, c_node_path.as_ptr(), child) };
```
Comment (weiznich) [inline src/spatial_ref/srs.rs:570]: `c_ptr` is owned by `c_node_path` here, so we don't need to free it?

File: src/spatial_ref/srs.rs [hunk 15]
```diff
@@ -379,7 +370,7 @@ impl SpatialRef {
     }
 
     pub fn axis_name(&self, target_key: &str, axis: i32) -> Result<String> {
-        // See get_axis_orientation
+        // See axis_orientation
         let c_ptr = unsafe {
```
Comment (weiznich) [inline src/spatial_ref/srs.rs:374]: axis names are assumed to be static, so no need to free it?

File: src/spatial_ref/srs.rs [hunk 16]
```diff
@@ -284,34 +284,25 @@ impl SpatialRef {
...
+        _string(c_ptr)
     }
 
     pub fn angular_units(&self) -> f64 {
         unsafe { gdal_sys::OSRGetAngularUnits(self.0, ptr::null_mut()) }
     }
 
-    pub fn linear_units_name(&self) -> Result<String> {
+    pub fn linear_units_name(&self) -> Option<String> {
         let mut c_ptr = ptr::null_mut();
```
Comment (weiznich) [inline src/spatial_ref/srs.rs:303]: unit names are assumed to be static, so again no need to free it?

File: src/spatial_ref/srs.rs [hunk 17]
```diff
@@ -284,34 +284,25 @@ impl SpatialRef {
...
-            return Err(_last_null_pointer_err("OSRGetName"));
-        }
-        Ok(_string(c_ptr))
+        _string(c_ptr)
     }
 
-    pub fn angular_units_name(&self) -> Result<String> {
+    pub fn angular_units_name(&self) -> Option<String> {
         let mut c_ptr = ptr::null_mut();
         unsafe { gdal_sys::OSRGetAngularUnits(self.0, &mut c_ptr) };
```
Comment (weiznich) [inline src/spatial_ref/srs.rs:294]: Angular units are assumed to be static, so no need to free them?

File: src/spatial_ref/srs.rs [hunk 18]
```diff
@@ -284,34 +284,25 @@ impl SpatialRef {
     }
 
     #[cfg(major_ge_3)]
-    pub fn name(&self) -> Result<String> {
+    pub fn name(&self) -> Option<String> {
         let c_ptr = unsafe { gdal_sys::OSRGetName(self.0) };
```
Comment (weiznich) [inline src/spatial_ref/srs.rs:288]: `c_ptr` is onwed by self, so we don't need to free it?

File: src/spatial_ref/srs.rs [hunk 19]
```diff
@@ -226,41 +226,41 @@ impl SpatialRef {
...
-            Ok(_string(c_projjsonstr))
+            Ok(_string(c_projjsonstr).unwrap_or_default())
         };
         unsafe { gdal_sys::VSIFree(c_projjsonstr.cast::<std::ffi::c_void>()) };
         res
     }
 
-    pub fn auth_name(&self) -> Result<String> {
+    pub fn auth_name(&self) -> Option<String> {
         let c_ptr = unsafe { gdal_sys::OSRGetAuthorityName(self.0, ptr::null()) };
```
Comment (weiznich) [inline src/spatial_ref/srs.rs:236]: The same is assumed to be owned by `self` so there is no need to free `c_ptr`?

File: src/raster/types.rs [hunk 20]
```diff
@@ -103,15 +103,7 @@ impl GdalDataType {
     /// ```
     pub fn name(&self) -> String {
         let c_str = unsafe { GDALGetDataTypeName(self.gdal_ordinal()) };
```
Comment (weiznich) [inline src/raster/types.rs:105]: `c_str` is owned by `self` so we don't need to free it?

File: src/raster/rasterband.rs [hunk 21]
```diff
@@ -1362,8 +1357,8 @@ impl ColorInterpretation {
 
     /// Returns the name of this color interpretation.
     pub fn name(&self) -> String {
-        let rv = unsafe { gdal_sys::GDALGetColorInterpretationName(self.c_int()) };
-        _string(rv)
+        let c_ptr = unsafe { gdal_sys::GDALGetColorInterpretationName(self.c_int()) };
```
Comment (weiznich) [inline src/raster/rasterband.rs:1360]: `c_ptr` is owned by `self` so we don't need to free it?

File: src/raster/rasterband.rs [hunk 22]
```diff
@@ -950,13 +950,8 @@ impl<'a> RasterBand<'a> {
...
     /// If there is no unit, the empty string is returned.
     pub fn unit(&self) -> String {
-        let str_ptr = unsafe { gdal_sys::GDALGetRasterUnitType(self.c_rasterband) };
-
-        if str_ptr.is_null() {
-            return String::new();
-        }
-
-        _string(str_ptr)
+        let c_ptr = unsafe { gdal_sys::GDALGetRasterUnitType(self.c_rasterband) };
```
Comment (weiznich) [inline src/raster/rasterband.rs:953]: `c_ptr` is owned by `self` so we don't need to free it?

File: src/raster/mdarray.rs [hunk 23]
```diff
@@ -767,12 +763,9 @@ impl Attribute {
...
 
     pub fn read_as_string(&self) -> String {
-        unsafe {
-            // SAFETY: should no be freed
-            let c_string = GDALAttributeReadAsString(self.c_attribute);
-
-            _string(c_string)
-        }
+        // should no be freed
+        let c_ptr = unsafe { GDALAttributeReadAsString(self.c_attribute) };
```
Comment (weiznich) [inline src/raster/mdarray.rs:767]: `c_ptr` is owned by `self` so we don't need to free it?

File: src/raster/mdarray.rs [hunk 24]
```diff
@@ -712,7 +707,8 @@ impl ExtendedDataType {
     }
 
     pub fn name(&self) -> String {
-        _string(unsafe { GDALExtendedDataTypeGetName(self.c_data_type) })
+        let c_ptr = unsafe { GDALExtendedDataTypeGetName(self.c_data_type) };
```
Comment (weiznich) [inline src/raster/mdarray.rs:710]: `c_ptr` is owned by `self` so we don't need to free it?

File: src/raster/mdarray.rs [hunk 25]
```diff
@@ -624,7 +618,8 @@ impl<'a> Dimension<'a> {
     }
 
     pub fn name(&self) -> String {
-        _string(unsafe { GDALDimensionGetName(self.c_dimension) })
+        let c_ptr = unsafe { GDALDimensionGetName(self.c_dimension) };
```
Comment (weiznich) [inline src/raster/mdarray.rs:621]: `c_ptr` is owned by `self` so we don't need to free it?

File: src/raster/mdarray.rs [hunk 26]
```diff
@@ -488,7 +481,8 @@ impl<'a> Group<'a> {
     }
 
     pub fn name(&self) -> String {
-        _string(unsafe { GDALGroupGetName(self.c_group) })
+        let c_ptr = unsafe { GDALGroupGetName(self.c_group) };
```
Comment (weiznich) [inline src/raster/mdarray.rs:484]: `c_ptr` is owned by `self` so we don't need to free it?

File: src/raster/mdarray.rs [hunk 27]
```diff
@@ -376,9 +370,8 @@ impl<'a> MDArray<'a> {
     pub fn unit(&self) -> String {
         unsafe {
             // should not be freed
-            let c_unit = GDALMDArrayGetUnit(self.c_mdarray);
-
-            _string(c_unit)
+            let c_ptr = GDALMDArrayGetUnit(self.c_mdarray);
```
Comment (weiznich) [inline src/raster/mdarray.rs:373]: `c_ptr` is owned by `self` so we don't need to free it?

File: src/raster/mdarray.rs [hunk 28]
```diff
@@ -331,16 +331,10 @@ impl<'a> MDArray<'a> {
...
-                    } else {
-                        let string = _string(string_ptr);
-
-                        VSIFree(string_ptr as *mut c_void);
-
-                        string
-                    }
+                .filter_map(|ptr| {
+                    let s = _string(ptr);
+                    VSIFree(ptr as *mut c_void);
```
Comment (weiznich) [inline src/raster/mdarray.rs:336]: ptr might here be actually null, free functions usually do not like to get a `nullptr` passed into them. Maybe better write

```
let s = _string(ptr)?;
VSIFree(ptr as *mut c_void);
Some(s)
```

File: src/metadata.rs [hunk 29]
```diff
@@ -59,10 +59,7 @@ pub trait Metadata: MajorObject {
     /// ```
     fn description(&self) -> Result<String> {
         let c_res = unsafe { gdal_sys::GDALGetDescription(self.gdal_object_ptr()) };
```
Comment (weiznich) [inline src/metadata.rs:61]: `c_res` is owned by self and we don't need to free it?

File: src/gcp.rs [hunk 30]
```diff
@@ -133,10 +133,7 @@ impl Dataset {
     ///  See: [`GDALGetGCPProjection`](https://gdal.org/api/raster_c_api.html#gdal_8h_1a85ffa184d3ecb7c0a59a66096b22b2ec)
     pub fn gcp_projection(&self) -> Option<String> {
         let cc_ptr = unsafe { gdal_sys::GDALGetGCPProjection(self.c_dataset()) };
```
Comment (weiznich) [inline src/gcp.rs:135]: `cc_ptr` is owned by self and we don't need to free it?

File: src/gcp.rs (hunk 2 above)
Comment (weiznich) [reply src/gcp.rs:85]: Maybe rather replace this function with a `Gcp::from_ptr(&gdal_sys::GDAL_GCP) -> Option<Gcp>` function?

File: src/driver.rs [hunk 31]
```diff
@@ -66,7 +66,7 @@ impl Driver {
     /// See also: [`long_name`](Self::long_name).
     pub fn short_name(&self) -> String {
         let rv = unsafe { gdal_sys::GDALGetDriverShortName(self.c_driver) };
```
Comment (weiznich) [inline src/driver.rs:68]: `rv` is owned by self, so we don't need to free it here?

File: src/driver.rs [hunk 32]
```diff
@@ -76,7 +76,7 @@ impl Driver {
     /// See also: [`short_name`](Self::short_name`).
     pub fn long_name(&self) -> String {
         let rv = unsafe { gdal_sys::GDALGetDriverLongName(self.c_driver) };
```
Comment (weiznich) [inline src/driver.rs:78]: `rv` is owned by self, so we don't need to free it here?

File: src/dataset.rs [hunk 33]
```diff
@@ -208,7 +208,7 @@ impl Dataset {
     /// Fetch the projection definition string for this dataset.
     pub fn projection(&self) -> String {
         let rv = unsafe { gdal_sys::GDALGetProjectionRef(self.c_dataset) };
```
Comment (weiznich) [inline src/dataset.rs:210]: `rv` is owned by self, so we don't need to free it here?

File: src/cpl.rs [hunk 34]
```diff
@@ -240,20 +235,13 @@ impl CslStringList {
         if index > c_int::MAX as usize {
             return None;
         }
+
         // In the C++ implementation, an index-out-of-bounds returns an empty string, not an error.
         // We don't want to check against `len` because that scans the list.
         // See: https://github.com/OSGeo/gdal/blob/fada29feb681e97f0fc4e8861e07f86b16855681/port/cpl_string.cpp#L181-L182
         let field = unsafe { CSLGetField(self.as_ptr(), index as c_int) };
```
Comment (weiznich) [inline src/cpl.rs:242]: `field` is owned by self, so we don't need to free it here?

File: src/cpl.rs [hunk 35]
```diff
@@ -505,12 +493,7 @@ impl<'a> Iterator for CslStringListIterator<'a> {
             slice[self.idx]
         };
         self.idx += 1;
-        if field.is_null() {
-            None
-        } else {
-            let entry = _string(field);
-            Some(entry.deref().into())
-        }
+        _string(field).map(|s| s.into())
```
Comment (weiznich) [inline src/cpl.rs:496]: `field` is owned by `self.list.list_ptr`, so we don't need to free it here?

File: src/cpl.rs [hunk 36]
```diff
@@ -178,11 +177,7 @@ impl CslStringList {
         // we know already `name` will never exist in a valid CslStringList.
         let key = CString::new(name).ok()?;
         let c_value = unsafe { CSLFetchNameValue(self.as_ptr(), key.as_ptr()) };
```
Comment (weiznich) [inline src/cpl.rs:179]: `c_value` is owned by self, so we don't need to free it here?

File: src/config.rs [hunk 37]
```diff
@@ -96,7 +96,7 @@ pub fn get_thread_local_config_option(key: &str, default: &str) -> Result<String
     let c_key = CString::new(key.as_bytes())?;
     let c_default = CString::new(default.as_bytes())?;
     let rv = unsafe { gdal_sys::CPLGetThreadLocalConfigOption(c_key.as_ptr(), c_default.as_ptr()) };
```
Comment (weiznich) [inline src/config.rs:98]: `rv` is points to a thread local, so we don't need to free it here?

File: src/config.rs [hunk 38]
```diff
@@ -55,7 +55,7 @@ pub fn get_config_option(key: &str, default: &str) -> Result<String> {
     let c_key = CString::new(key.as_bytes())?;
     let c_default = CString::new(default.as_bytes())?;
     let rv = unsafe { gdal_sys::CPLGetConfigOption(c_key.as_ptr(), c_default.as_ptr()) };
```
Comment (weiznich) [inline src/config.rs:57]: `rv` is points to a global variable so we don't need to free it here?

**Review by weiznich — COMMENTED** [review]
I think overall that is a good change.

I'm relatively new to the low level gdal interfaces, so I added "some" questions around which pointer comes from where. Feel free to dismiss them in batch if the assumptions written down there are correct, although it might be good to just put that as comments into the code.

I think in one location I might have discovered a problematic free call.

File: src/version.rs (hunk 3 above)
Comment (lnicola) [reply src/version.rs:57]: I think it's more complicated (it's a string that GDAL formats and stores in TLS IIRC), but according to the docs:

> an internal string containing the requested information

So we can treat it as static.

File: src/vector/layer.rs (hunk 4 above)
Comment (lnicola) [reply src/vector/layer.rs:286]: > the layer name (must not been freed)

File: src/vector/geometry.rs (hunk 5 above)
Comment (lnicola) [reply src/vector/geometry.rs:356]: > internal human readable string, or NULL on failure.

(but it's never NULL in the current implementation, it returns something like "Unrecognized: XXXX" in a static buffer)

File: src/vector/geometry.rs (hunk 6 above)
Comment (lnicola) [reply src/vector/geometry.rs:172]: Apparently so, it returns a static string.

File: src/vector/feature.rs (hunk 7 above)
Comment (lnicola) [reply src/vector/feature.rs:837]: Yes, returns a static string, never NULL.

File: src/vector/feature.rs (hunk 8 above)
Comment (lnicola) [reply src/vector/feature.rs:626]: Yes, it's owned by the field (I think it's a general pattern with `GetFooRef()`).

File: src/vector/feature.rs (hunk 9 above)
Comment (lnicola) [reply src/vector/feature.rs:92]: Yes:

> This string is internal, and should not be modified, or freed. Its lifetime may be very brief.

File: src/vector/defn.rs (hunk 10 above)
Comment (lnicola) [reply src/vector/defn.rs:205]: Yes, owned by `OGRGeomFieldDefn`.

File: src/vector/defn.rs (hunk 11 above)
Comment (lnicola) [reply src/vector/defn.rs:165]: Owned by `OGRFieldDefn`.

File: src/raster/mdarray.rs (hunk 28 above)
Comment (lnicola) [reply src/raster/mdarray.rs:336]: @rouault would you take a GDAL doc PR to explicitly mention that `VSIFree` can be called with a null pointer?

File: src/vector/defn.rs (hunk 12 above)
Comment (lnicola) [reply src/vector/defn.rs:130]: Yes, owned by `OGRFieldDefn`.

File: src/spatial_ref/srs.rs (hunk 14 above)
Comment (lnicola) [reply src/spatial_ref/srs.rs:570]: Yes, owned by the `OGR_SRSNode`.

File: src/spatial_ref/srs.rs (hunk 15 above)
Comment (lnicola) [reply src/spatial_ref/srs.rs:374]: Comes from `OGR_SRSNode`.

File: src/spatial_ref/srs.rs (hunk 16 above)
Comment (lnicola) [reply src/spatial_ref/srs.rs:303]: Owned by `OGRSpatialReference`.

File: src/spatial_ref/srs.rs (hunk 17 above)
Comment (lnicola) [reply src/spatial_ref/srs.rs:294]: Owned by `OGRSpatialReference`.

File: src/spatial_ref/srs.rs (hunk 18 above)
Comment (lnicola) [reply src/spatial_ref/srs.rs:288]: Owned by PROJ via `OGRSpatialReference`.

File: src/spatial_ref/srs.rs (hunk 19 above)
Comment (lnicola) [reply src/spatial_ref/srs.rs:236]: Owned by PROJ via `OGRSpatialReference`.

File: src/raster/types.rs (hunk 20 above)
Comment (lnicola) [reply src/raster/types.rs:105]: `GDALGetDataTypeName` returns static strings.

File: src/raster/rasterband.rs (hunk 21 above)
Comment (lnicola) [reply src/raster/rasterband.rs:1360]: `GDALGetColorInterpretationName` returns static strings.

File: src/raster/rasterband.rs (hunk 22 above)
Comment (lnicola) [reply src/raster/rasterband.rs:953]: Owned by `GDALRasterBand`.

> The returned string should not be modified, nor freed by the calling application.

File: src/version.rs (hunk 3 above)
Comment (rouault) [reply src/version.rs:57]: > Do we need to free `rv` here?

As a rule of thumb, that part of the GDAL C API should be relatively easy to get:
- For C/C++ functions that return a "const char*", as a "const char*" cannot be passed directly to C free(),  that indicates that the returned value should not be freed
- And the documentation of functions where the return value must be freed indicates so, and generally will specify which free function is expected. (like OGR_G_DestroyGeometry() for anything OGRGeometryH related, etc)

File: src/gcp.rs (hunk 2 above)
Comment (lnicola) [reply src/gcp.rs:85]: I think it's fine, they docs say about `pszInfo`:

> Informational message or "". 

GDAL calls `json_object_new_string` on them [here](https://github.com/OSGeo/gdal/blob/0caa252cda18ce1e68028403b9719e3ca898ae50/apps/gdalinfo_lib.cpp#L806-L807), which [assumes](https://github.com/OSGeo/gdal/blob/0caa252cda18ce1e68028403b9719e3ca898ae50/ogr/ogrsf_frmts/geojson/libjson/json_object.c#L1307) that the pointer is non-null by calling `strlen` on it.

And in most places `pszInfo` is initialized with `CSLStrDup("")`, which matches the docs. As for `pszid`, that's usually initialized with a number, I don't think it can be null.

File: src/utils.rs [hunk 39]
```diff
@@ -5,35 +5,40 @@ use gdal_sys::CPLErr;
 
 use crate::errors::*;
 
-pub fn _string(raw_ptr: *const c_char) -> String {
-    let c_str = unsafe { CStr::from_ptr(raw_ptr) };
-    c_str.to_string_lossy().into_owned()
-}
-
-pub(crate) fn _string_tuple(raw_ptr: *const c_char, delim: char) -> Option<(String, String)> {
```
Comment (lnicola) [inline src/utils.rs:13]: This was also unsound, but never used.
